version: "3.1"
services:

  mongo1:
    container_name: mongo_rs1
    image: mongo:4.2.3
    ports:
      - 27018:27017
    restart: always
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0"]

  mongo2:
    container_name: mongo_rs2
    image: mongo:4.2.3
    ports:
      - 27019:27017
    restart: always
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0"]
      
  mongo3:
    container_name: mongo_rs3
    image: mongo:4.2.3
    ports:
      - 27020:27017
    restart: always
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0"]
